version: 2.1 
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget llvm python gcc clang libssl-dev
           git clone --depth=1 https://github.com/Dhruvgera/RockstarKernel_beryllium.git -b rebase2
           cd RockstarKernel_beryllium
           bash unified.sh 
           bash unified.sh -clean
           sed -i "s/qcom,mdss-dsi-panel-framerate = <60>/qcom,mdss-dsi-panel-framerate = <70>/g" $PWD/arch/arm64/boot/dts/qcom/dsi-panel-ebbg-fhd-ft8719-video.dtsi
           sed -i "s/qcom,mdss-dsi-panel-framerate = <60>/qcom,mdss-dsi-panel-framerate = <70>/g" $PWD/arch/arm64/boot/dts/qcom/dsi-panel-tianma-fhd-nt36672a-video.dtsi
           bash unified.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
